**AWS Data Collection**

In [1]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://aws.amazon.com/about-aws/global-infrastructure/"

response = requests.get(url)

print(response.status_code)

200

In [4]:
print(response.text[:1000])

<!doctype html>
<html lang="en-US" data-static-assets="https://a0.awsstatic.com" class="aws-lng-en_US">
 <head>
  <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: https://a0.awsstatic.com https://prod.us-east-1.ui.gcr-chat.marketing.aws.dev; base-uri 'none'; connect-src 'self' https://*.analytics.console.aws.a2z.com https://*.corrivium.live https://*.harmony.a2z.com https://*.marketing.aws.dev https://*.panorama.console.api.aws https://*.prod.chc-features.uxplatform.aws.dev https://*.prod.cxm.marketing.aws.dev https://*.us-east-1.prod.mrc-sunrise.marketing.aws.dev https://0vctm1i0if.execute-api.eusc-de-east-1.amazonaws.eu/gamma/spot.json https://112-tzm-766.mktoresp.com https://112-tzm-766.mktoutil.com https://8810.clrt.ai https://a0.awsstatic.com https://a0.p.awsstatic.com https://a1.awsstatic.com https://amazonwebservices.d2.sc.omtrdc.net https://amazonwebservicesinc.tt.omtrdc.net https://api-v2.builderprofile.aws.dev https://api.regional-table.region-serv

In [5]:
from bs4 import BeautifulSoup
import pandas as pd
import re

soup = BeautifulSoup(response.text, "html.parser")

text = soup.get_text(" ", strip=True)

print(text[:3000])

Global Infrastructure -  AWS Skip to main content Filter: All English Contact us AWS Marketplace Support My account Search Filter: All Sign in to console Create account AWS Homepage AWS Global infrastructure AWS Global Infrastructure Build your applications with confidence on the most secure, reliable, and extensive global cloud infrastructure Create account Explore regional services AWS Global Infrastructure Solutions Digital Sovereignty Sustainability & Community Regional Services Innovation Why AWS Global Infrastructure matters AWS global infrastructure is the most secure, reliable, and extensive cloud, providing diverse infrastructure solutions for running your applications anywhere. With three Availability Zones (AZs) per Region and optimized data centers, AWS global infrastructure maximizes resilience, performance, and innovation. With nearly 20 million kilometers of fiber optic cabling, AWS’s global network backbone enables faster data transfer, reduced latency, and enhanced application performance. Play AWS Global Infrastructure The AWS Cloud spans 123 Availability Zones within 39 Geographic Regions, with announced plans for 7 more Availability Zones and 2 more AWS Regions in the Kingdom of Saudi Arabia, and Chile. North America South America Europe Middle East Africa Asia Pacific Australia and New Zealand AWS Coverage Regions North America Geographic Regions 9 AWS GovCloud (US-East) AWS GovCloud (US-West) Canada (Central) Canada West (Calgary) Mexico (Central) US West (Northern California) US East (Northern Virginia) US East (Ohio) US West (Oregon) Available Coming soon Edge Locations 31 The AWS Cloud in North America has 31 Availability Zones within 9 Geographic Regions, with 31 Edge Network Locations and 3 Edge Cache Locations. Ashburn, VA Atlanta. GA Boston, MA Chicago, IL Columbus, OH Dallas/Fort Worth, TX Denver, CO Hayward, CA Houston, TX Jacksonville, FL Kansas City, MO Los Angeles, CA Miami, FL Minneapolis, MN Montreal, QC Nashville, TN New York, NY Newark, NJ Palo Alto, CA Phoenix, AZ Philadelphia, PA Portland, OR Queretaro, MX Salt Lake City, UT San Jose, CA Seattle, WA South Bend, IN St. Louis, MO Tampa Bay, FL Toronto, ON Washington D.C. The most extensive global cloud infrastructure 39 launched Regions each with multiple Availability Zones 123 Availability Zones 750+ CloudFront POPs and 15 Regional edge caches 43 Local Zones & 33 Wavelength Zones for low latency applications What's new in AWS Global Infrastructure What's New AWS launches a new Regional planning tool called AWS Capabilities by Region Read more What's New AWS launches a new region in New Zealand Read more What's New Amazon investing AU$20 billion to expand data center infrastructure in Australia Read more What's New AWS launches a new region in Taiwan Read more What's New AWS announces a new region in Chile Read more Benefits of the AWS Global Infrastructure Most secure and reliable infrastructure AWS is architected to be the most secure global cloud infrastru

In [6]:
keywords = ["US East", "US West", "Canada", "Asia Pacific", "Europe", "Middle East"]

for k in keywords:
    print(k, text.find(k))

US East 1524
US West 1494
Canada 1438
Asia Pacific 1297
Europe 1271
Middle East 1278

In [7]:
aws_regions = [
    ["AWS", "North America", "US East (N. Virginia)", "Available"],
    ["AWS", "North America", "US East (Ohio)", "Available"],
    ["AWS", "North America", "US West (N. California)", "Available"],
    ["AWS", "North America", "US West (Oregon)", "Available"],
    ["AWS", "North America", "Canada (Central)", "Available"],
    ["AWS", "North America", "Canada West (Calgary)", "Available"],
    ["AWS", "North America", "Mexico (Central)", "Available"],
]

aws_df = pd.DataFrame(
    aws_regions,
    columns=["provider", "continent", "region_name", "status"]
)

aws_df

  provider      continent              region_name     status
0      AWS  North America    US East (N. Virginia)  Available
1      AWS  North America           US East (Ohio)  Available
2      AWS  North America  US West (N. California)  Available
3      AWS  North America         US West (Oregon)  Available
4      AWS  North America         Canada (Central)  Available
5      AWS  North America    Canada West (Calgary)  Available
6      AWS  North America         Mexico (Central)  Available

In [8]:
aws_df.to_csv("aws_regions.csv", index=False)

**Azure Data Collection**

In [9]:
import requests
from bs4 import BeautifulSoup

url = "https://azure.microsoft.com/en-us/explore/global-infrastructure/"

response = requests.get(url)

print(response.status_code)

200

In [10]:
print(response.text[:1000])

<!DOCTYPE HTML> <html lang="en-US" dir="ltr"> <head>        <meta charset="UTF-8"/> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/> <meta http-equiv="x-ua-compatible" content="ie=edge"/> <meta name="content-page-ref" content="oGw4a85CnCDglGADCsJX9_SF1UIpKQRLwBdl2ySXPA83_FH7VMdF1d6om_duDY6H3paEwsfltmcQGC_8BUIl0NTE8dSqK-y_Wf6_zlyVkVw"/>
<script defer="defer" type="text/javascript" src="https://rum.hlx.page/.rum/@adobe/helix-rum-js@%5E2/dist/micro.js" data-routing="program=147723,environment=1510601,tier=publish"></script>
<link rel="icon" href="/favicon.ico?v2" type="image/x-icon"/> <meta name="robots" content="index, follow"/> <meta name="template" content="reimagine---azure-pdp-template-v2"/> <meta name="awa-canvasType" content="web"/> <meta name="awa-isTented" content="false"/> <meta name="awa-pgtmp" content="reimagine---azure-pdp-template-v2"/> <meta name="awa-pageType" content="Azure"/> <meta name="awa-market" content="en-us"/> <meta name="awa

In [11]:
azure_regions = [
    ["Azure", "North America", "East US", "Available"],
    ["Azure", "North America", "East US 2", "Available"],
    ["Azure", "North America", "Central US", "Available"],
    ["Azure", "North America", "West US", "Available"],
    ["Azure", "North America", "West US 2", "Available"],
    ["Azure", "North America", "Canada Central", "Available"],
    ["Azure", "North America", "Canada East", "Available"],
]

azure_df = pd.DataFrame(
    azure_regions,
    columns=["provider", "continent", "region_name", "status"]
)

azure_df

  provider      continent     region_name     status
0    Azure  North America         East US  Available
1    Azure  North America       East US 2  Available
2    Azure  North America      Central US  Available
3    Azure  North America         West US  Available
4    Azure  North America       West US 2  Available
5    Azure  North America  Canada Central  Available
6    Azure  North America     Canada East  Available

In [12]:
azure_df.to_csv("azure_regions.csv", index=False)

**合併AWS & AZURE**

In [13]:
combined_df = pd.concat([aws_df, azure_df], ignore_index=True)

combined_df

   provider      continent              region_name     status
0       AWS  North America    US East (N. Virginia)  Available
1       AWS  North America           US East (Ohio)  Available
2       AWS  North America  US West (N. California)  Available
3       AWS  North America         US West (Oregon)  Available
4       AWS  North America         Canada (Central)  Available
5       AWS  North America    Canada West (Calgary)  Available
6       AWS  North America         Mexico (Central)  Available
7     Azure  North America                  East US  Available
8     Azure  North America                East US 2  Available
9     Azure  North America               Central US  Available
10    Azure  North America                  West US  Available
11    Azure  North America                West US 2  Available
12    Azure  North America           Canada Central  Available
13    Azure  North America              Canada East  Available

**GCP Data Collection**

In [14]:
import requests
from bs4 import BeautifulSoup

url = "https://cloud.google.com/about/locations"

response = requests.get(url)

print(response.status_code)

200

In [15]:
print(response.text[:1000])

<!doctype html>
<html
      lang="en"
      dir="ltr">
  <head>
    <meta name="google-signin-client-id" content="721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com"><meta name="google-signin-scope"
          content="profile email https://www.googleapis.com/auth/developerprofiles https://www.googleapis.com/auth/developerprofiles.award https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/webhistory https://www.googleapis.com/auth/devprofiles.full_control.firstparty"><meta property="og:site_name" content="Google Cloud">
    <meta property="og:type" content="website"><meta name="theme-color" content="#039be5"><meta charset="utf-8">
    <meta content="IE=Edge" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="manifest" href="/_pwa/cloud/manifest.json"
          crossorigin="use-credentials">
    <link rel="preconnect" href="//www.gstatic.com" crossorigin>

In [16]:
gcp_regions = [
    ["GCP", "North America", "us-central1 (Iowa)", "Available"],
    ["GCP", "North America", "us-east1 (South Carolina)", "Available"],
    ["GCP", "North America", "us-east4 (Northern Virginia)", "Available"],
    ["GCP", "North America", "us-west1 (Oregon)", "Available"],
    ["GCP", "North America", "northamerica-northeast1 (Montreal)", "Available"],
    ["GCP", "Europe", "europe-west1 (Belgium)", "Available"],
    ["GCP", "Asia Pacific", "asia-east1 (Taiwan)", "Available"],
]

gcp_df = pd.DataFrame(
    gcp_regions,
    columns=["provider", "continent", "region_name", "status"]
)

gcp_df

  provider      continent                         region_name     status
0      GCP  North America                  us-central1 (Iowa)  Available
1      GCP  North America           us-east1 (South Carolina)  Available
2      GCP  North America        us-east4 (Northern Virginia)  Available
3      GCP  North America                   us-west1 (Oregon)  Available
4      GCP  North America  northamerica-northeast1 (Montreal)  Available
5      GCP         Europe              europe-west1 (Belgium)  Available
6      GCP   Asia Pacific                 asia-east1 (Taiwan)  Available

In [17]:
gcp_df.to_csv("gcp_regions.csv", index=False)

**三家合併**

In [18]:
multi_cloud_df = pd.concat(
    [aws_df, azure_df, gcp_df],
    ignore_index=True
)

multi_cloud_df

   provider      continent                         region_name     status
0       AWS  North America               US East (N. Virginia)  Available
1       AWS  North America                      US East (Ohio)  Available
2       AWS  North America             US West (N. California)  Available
3       AWS  North America                    US West (Oregon)  Available
4       AWS  North America                    Canada (Central)  Available
5       AWS  North America               Canada West (Calgary)  Available
6       AWS  North America                    Mexico (Central)  Available
7     Azure  North America                             East US  Available
8     Azure  North America                           East US 2  Available
9     Azure  North America                          Central US  Available
10    Azure  North America                             West US  Available
11    Azure  North America                           West US 2  Available
12    Azure  North America                      Canada Central  Available
13    Azure  North America                         Canada East  Available
14      GCP  North America                  us-central1 (Iowa)  Available
15      GCP  North America           us-east1 (South Carolina)  Available
16      GCP  North America        us-east4 (Northern Virginia)  Available
17      GCP  North America                   us-west1 (Oregon)  Available
18      GCP  North America  northamerica-northeast1 (Montreal)  Available
19      GCP         Europe              europe-west1 (Belgium)  Available
20      GCP   Asia Pacific                 asia-east1 (Taiwan)  Available

**儲存資料**

In [19]:
multi_cloud_df.to_csv("multi_cloud_regions.csv", index=False)

In [20]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

text = soup.get_text(" ", strip=True)

print(text[:5000])

Global Locations - Regions & Zones  |  Google Cloud Skip to main content Overview close Accelerate your digital transformation Whether your business is early in its journey or well on its way to digital transformation, Google Cloud can help solve your toughest challenges. Learn more Key benefits Why Google Cloud Top reasons businesses choose us. AI and Agents Get enterprise-ready AI. Multicloud Run your apps wherever you need them. Global infrastructure Build on the same infrastructure as Google. Data Cloud Make smarter decisions with unified data. Modern Infrastructure Cloud Next generation of cloud infrastructure. Security Protect your users, data, and apps. Productivity and collaboration Connect your teams with AI-powered apps. Reports and insights Executive insights Curated C-suite perspectives. Analyst reports Read what industry analysts say about us. Whitepapers Browse and download popular whitepapers. Customer stories Explore case studies and videos. Solutions close Industry Solutions Reduce cost, increase operational agility, and capture new market opportunities. Retail Analytics and collaboration tools for the retail value chain. Consumer Packaged Goods Solutions for CPG digital transformation and brand growth. Financial Services Computing, data management, and analytics tools for financial services. Healthcare and Life Sciences Advance research at scale and empower healthcare innovation. Media and Entertainment Solutions for content production and distribution operations. Telecommunications Hybrid and multi-cloud services to deploy and monetize 5G. Games AI-driven solutions to build and scale games faster. Manufacturing Migration and AI tools to optimize the manufacturing value chain. Supply Chain and Logistics Enable sustainable, efficient, and resilient data-driven operations across supply chain and logistics operations. Government Data storage, AI, and analytics solutions for government agencies. Education Teaching tools to provide more engaging learning experiences. Not seeing what you're looking for? See all industry solutions Not seeing what you're looking for? See all solutions Application Modernization Assess, plan, implement, and measure software practices and capabilities to modernize and simplify your organization’s business application portfolios. CAMP Program that uses DORA to improve your software delivery capabilities. Modernize Traditional Applications Analyze, categorize, and get started with cloud migration on traditional workloads. Migrate from PaaS: Cloud Foundry, Openshift Tools for moving your existing containers into Google's managed container services. Migrate from Mainframe Automated tools and prescriptive guidance for moving your mainframe apps to the cloud. Modernize Software Delivery Software supply chain best practices - innerloop productivity, CI/CD and S3C. DevOps Best Practices Processes and resources for implementing DevOps in your org. SRE Principles Tools and resources for adopting SRE in your org. Platform Engineering Comprehensive suite of managed services and Golden Paths to build, manage, and scale IDPs. Architect for Multicloud Manage workloads across multiple clouds with a consistent platform. Artificial Intelligence Add intelligence and efficiency to your business with AI and machine learning. Gemini Enterprise for Customer Experience Build and manage agents that live across the entire customer lifecycle. Gemini Enterprise Unified agentic portfolio for your entire organization. AI Commerce Search Google-quality search and product recommendations for retailers. Google Cloud with Gemini AI assistants for application development, coding, and more. Physical AI Simulate, train, and operate the next generation of robots, autonomous vehicles, industrial devices, and machines. APIs and Applications Speed up the pace of innovation without coding, using APIs, apps, and automation. New Business Channels Using APIs Attract and empower an ecosystem of developers and partners. Unlocking Legacy Applications Using APIs Cloud services for extending and modernizing legacy apps. Open Banking APIx Simplify and accelerate secure delivery of open banking compliant APIs. Data Analytics Generate instant insights from data at any scale with a serverless, fully managed analytics platform that significantly simplifies analytics. Data Migration Migrate and modernize your data warehouse and data lakes with AI-powered migration services. Data Lakehouse Unify and govern your multimodal data with a high-performance and open data lakehouse. Real-time Analytics Insights from ingesting, processing, and analyzing event streams. Marketing Analytics Solutions for collecting, analyzing, and activating customer data. Datasets Data from Google, public, and commercial providers to enrich your analytics and AI initiatives. Business Intelligence Solutions for modernizing your BI stack and creating rich data experiences. Data Analytics Agents Built-in agents for data lifecycle and tools to build your

In [21]:
import requests
import pandas as pd

url = "https://raw.githubusercontent.com/jsonmaur/aws-regions/master/regions.json"

data = requests.get(url).json()

aws_df = pd.DataFrame(data)

aws_df.head()

,name,full_name,code,public,zones,zone_limit
0,N. Virginia,US East (N. Virginia),us-east-1,True,"[us-east-1a, us-east-1b, us-east-1c, us-east-1...",NaN
1,Ohio,US East (Ohio),us-east-2,True,"[us-east-2a, us-east-2b, us-east-2c]",NaN
2,N. California,US West (N. California),us-west-1,True,"[us-west-1a, us-west-1b, us-west-1c]",2.0
3,Oregon,US West (Oregon),us-west-2,True,"[us-west-2a, us-west-2b, us-west-2c, us-west-2d]",NaN
4,GovCloud West,AWS GovCloud (US),us-gov-west-1,False,"[us-gov-west-1a, us-gov-west-1b, us-gov-west-1c]",NaN

In [22]:
!pip install boto3

import boto3
import pandas as pd

session = boto3.session.Session()

aws_regions = session.get_available_regions("ec2")

aws_df = pd.DataFrame({
    "provider": "AWS",
    "service": "EC2",
    "region_code": aws_regions
})

aws_df.head()

Collecting boto3
  Downloading boto3-1.43.16-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.44.0,>=1.43.16 (from boto3)
  Downloading botocore-1.43.16-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.18.0,>=0.17.0 (from boto3)
  Downloading s3transfer-0.17.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<1.44.0,>=1.43.16->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.44.0,>=1.43.16->boto3) (2.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.16->boto3) (1.17.0)
Downloading boto3-1.43.16-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.5/140.5 kB 3.4 MB/s eta 0:00:00
Downloading botocore-1.43.16-py3-none-any.whl (15.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 67.4 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.17.1-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 7.6 MB/s eta 0:00:00
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.43.16 botocore-1.43.16 jmespath-1.1.0 s3transfer-0.17.1

  provider service     region_code
0      AWS     EC2      af-south-1
1      AWS     EC2       ap-east-1
2      AWS     EC2       ap-east-2
3      AWS     EC2  ap-northeast-1
4      AWS     EC2  ap-northeast-2

In [23]:
azure_regions = [
    ["Azure", "East US", "eastus", "North America"],
    ["Azure", "East US 2", "eastus2", "North America"],
    ["Azure", "Central US", "centralus", "North America"],
    ["Azure", "West US", "westus", "North America"],
    ["Azure", "West US 2", "westus2", "North America"],

    ["Azure", "Canada Central", "canadacentral", "North America"],
    ["Azure", "Brazil South", "brazilsouth", "South America"],

    ["Azure", "UK South", "uksouth", "Europe"],
    ["Azure", "France Central", "francecentral", "Europe"],
    ["Azure", "Germany West Central", "germanywestcentral", "Europe"],

    ["Azure", "Japan East", "japaneast", "Asia Pacific"],
    ["Azure", "Korea Central", "koreacentral", "Asia Pacific"],
    ["Azure", "Southeast Asia", "southeastasia", "Asia Pacific"],
    ["Azure", "Australia East", "australiaeast", "Oceania"],

    ["Azure", "UAE North", "uaenorth", "Middle East"],
    ["Azure", "South Africa North", "southafricanorth", "Africa"]
]

In [24]:
azure_df = pd.DataFrame(
    azure_regions,
    columns=[
        "provider",
        "region_name",
        "region_code",
        "continent"
    ]
)

azure_df.head()

  provider region_name region_code      continent
0    Azure     East US      eastus  North America
1    Azure   East US 2     eastus2  North America
2    Azure  Central US   centralus  North America
3    Azure     West US      westus  North America
4    Azure   West US 2     westus2  North America

In [25]:
azure_df["is_public"] = True

In [26]:
azure_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   provider     16 non-null     object
 1   region_name  16 non-null     object
 2   region_code  16 non-null     object
 3   continent    16 non-null     object
 4   is_public    16 non-null     bool
dtypes: bool(1), object(4)
memory usage: 660.0+ bytes

In [27]:
multi_cloud_df = pd.concat([
    aws_df,
    azure_df,
    gcp_df
], ignore_index=True)
print(multi_cloud_df)

   provider service         region_code                         region_name  \
0       AWS     EC2          af-south-1                                 NaN
1       AWS     EC2           ap-east-1                                 NaN
2       AWS     EC2           ap-east-2                                 NaN
3       AWS     EC2      ap-northeast-1                                 NaN
4       AWS     EC2      ap-northeast-2                                 NaN
5       AWS     EC2      ap-northeast-3                                 NaN
6       AWS     EC2          ap-south-1                                 NaN
7       AWS     EC2          ap-south-2                                 NaN
8       AWS     EC2      ap-southeast-1                                 NaN
9       AWS     EC2      ap-southeast-2                                 NaN
10      AWS     EC2      ap-southeast-3                                 NaN
11      AWS     EC2      ap-southeast-4                                 NaN
12      AWS     EC2      ap-southeast-5                                 NaN
13      AWS     EC2      ap-southeast-6                                 NaN
14      AWS     EC2      ap-southeast-7                                 NaN
15      AWS     EC2        ca-central-1                                 NaN
16      AWS     EC2           ca-west-1                                 NaN
17      AWS     EC2        eu-central-1                                 NaN
18      AWS     EC2        eu-central-2                                 NaN
19      AWS     EC2          eu-north-1                                 NaN
20      AWS     EC2          eu-south-1                                 NaN
21      AWS     EC2          eu-south-2                                 NaN
22      AWS     EC2           eu-west-1                                 NaN
23      AWS     EC2           eu-west-2                                 NaN
24      AWS     EC2           eu-west-3                                 NaN
25      AWS     EC2        il-central-1                                 NaN
26      AWS     EC2        me-central-1                                 NaN
27      AWS     EC2          me-south-1                                 NaN
28      AWS     EC2        mx-central-1                                 NaN
29      AWS     EC2           sa-east-1                                 NaN
30      AWS     EC2           us-east-1                                 NaN
31      AWS     EC2           us-east-2                                 NaN
32      AWS     EC2           us-west-1                                 NaN
33      AWS     EC2           us-west-2                                 NaN
34    Azure     NaN              eastus                             East US
35    Azure     NaN             eastus2                           East US 2
36    Azure     NaN           centralus                          Central US
37    Azure     NaN              westus                             West US
38    Azure     NaN             westus2                           West US 2
39    Azure     NaN       canadacentral                      Canada Central
40    Azure     NaN         brazilsouth                        Brazil South
41    Azure     NaN             uksouth                            UK South
42    Azure     NaN       francecentral                      France Central
43    Azure     NaN  germanywestcentral                Germany West Central
44    Azure     NaN           japaneast                          Japan East
45    Azure     NaN        koreacentral                       Korea Central
46    Azure     NaN       southeastasia                      Southeast Asia
47    Azure     NaN       australiaeast                      Australia East
48    Azure     NaN            uaenorth                           UAE North
49    Azure     NaN    southafricanorth                  South Africa North
50      GCP     NaN                 NaN                  us-central1 (Iowa)
51      GCP     NaN                 NaN           us-east1 (South Carolina)
52      GCP     NaN                 NaN        us-east4 (Northern Virginia)
53      GCP     NaN                 NaN                   us-west1 (Oregon)
54      GCP     NaN                 NaN  northamerica-northeast1 (Montreal)
55      GCP     NaN                 NaN              europe-west1 (Belgium)
56      GCP     NaN                 NaN                 asia-east1 (Taiwan)

        continent is_public     status
0             NaN       NaN        NaN
1             NaN       NaN        NaN
2             NaN       NaN        NaN
3             NaN       NaN        NaN
4             NaN       NaN        NaN
5             NaN       NaN        NaN
6             NaN       NaN        NaN
7             NaN       NaN        NaN
8             NaN       NaN        NaN
9             NaN       NaN        NaN
10            NaN       NaN        NaN
11            NaN       NaN        NaN
12            NaN       NaN        NaN
13            NaN       NaN        NaN
14            NaN       NaN        NaN
15            NaN       NaN        NaN
16            NaN       NaN        NaN
17            NaN       NaN        NaN
18            NaN       NaN        NaN
19            NaN       NaN        NaN
20            NaN       NaN        NaN
21            NaN       NaN        NaN
22            NaN       NaN        NaN
23            NaN       NaN        NaN
24            NaN       NaN        NaN
25            NaN       NaN        NaN
26            NaN       NaN        NaN
27            NaN       NaN        NaN
28            NaN       NaN        NaN
29            NaN       NaN        NaN
30            NaN       NaN        NaN
31            NaN       NaN        NaN
32            NaN       NaN        NaN
33            NaN       NaN        NaN
34  North America      True        NaN
35  North America      True        NaN
36  North America      True        NaN
37  North America      True        NaN
38  North America      True        NaN
39  North America      True        NaN
40  South America      True        NaN
41         Europe      True        NaN
42         Europe      True        NaN
43         Europe      True        NaN
44   Asia Pacific      True        NaN
45   Asia Pacific      True        NaN
46   Asia Pacific      True        NaN
47        Oceania      True        NaN
48    Middle East      True        NaN
49         Africa      True        NaN
50  North America       NaN  Available
51  North America       NaN  Available
52  North America       NaN  Available
53  North America       NaN  Available
54  North America       NaN  Available
55         Europe       NaN  Available
56   Asia Pacific       NaN  Available

In [28]:
# Fix GCP region_code from region_name
gcp_df["region_code"] = gcp_df["region_name"].str.extract(r"^([a-z0-9-]+)")
gcp_df["service"] = "Cloud Platform"
gcp_df["is_public"] = True
gcp_df["status"] = "Available"

# Fix Azure columns
azure_df["service"] = "Cloud Platform"
azure_df["status"] = "Available"

# Fix AWS columns
aws_df["region_name"] = aws_df["region_code"]
aws_df["service"] = "EC2"
aws_df["is_public"] = True
aws_df["status"] = "Available"

def map_continent(code):
    if code.startswith(("us-", "ca-", "mx-")):
        return "North America"
    elif code.startswith("sa-"):
        return "South America"
    elif code.startswith("eu-"):
        return "Europe"
    elif code.startswith(("ap-",)):
        return "Asia Pacific"
    elif code.startswith("me-") or code.startswith("il-"):
        return "Middle East"
    elif code.startswith("af-"):
        return "Africa"
    else:
        return "Other"

aws_df["continent"] = aws_df["region_code"].apply(map_continent)

# Standardize final columns
final_columns = [
    "provider",
    "service",
    "region_code",
    "region_name",
    "continent",
    "is_public",
    "status"
]

multi_cloud_df = pd.concat([
    aws_df[final_columns],
    azure_df[final_columns],
    gcp_df[final_columns]
], ignore_index=True)

multi_cloud_df

,provider,service,region_code,region_name,continent,is_public,status
0,AWS,EC2,af-south-1,af-south-1,Africa,True,Available
1,AWS,EC2,ap-east-1,ap-east-1,Asia Pacific,True,Available
2,AWS,EC2,ap-east-2,ap-east-2,Asia Pacific,True,Available
3,AWS,EC2,ap-northeast-1,ap-northeast-1,Asia Pacific,True,Available
4,AWS,EC2,ap-northeast-2,ap-northeast-2,Asia Pacific,True,Available
5,AWS,EC2,ap-northeast-3,ap-northeast-3,Asia Pacific,True,Available
6,AWS,EC2,ap-south-1,ap-south-1,Asia Pacific,True,Available
7,AWS,EC2,ap-south-2,ap-south-2,Asia Pacific,True,Available
8,AWS,EC2,ap-southeast-1,ap-southeast-1,Asia Pacific,True,Available
9,AWS,EC2,ap-southeast-2,ap-southeast-2,Asia Pacific,True,Available
10,AWS,EC2,ap-southeast-3,ap-southeast-3,Asia Pacific,True,Available
11,AWS,EC2,ap-southeast-4,ap-southeast-4,Asia Pacific,True,Available
12,AWS,EC2,ap-southeast-5,ap-southeast-5,Asia Pacific,True,Available
13,AWS,EC2,ap-southeast-6,ap-southeast-6,Asia Pacific,True,Available
14,AWS,EC2,ap-southeast-7,ap-southeast-7,Asia Pacific,True,Available
15,AWS,EC2,ca-central-1,ca-central-1,North America,True,Available
16,AWS,EC2,ca-west-1,ca-west-1,North America,True,Available
17,AWS,EC2,eu-central-1,eu-central-1,Europe,True,Available
18,AWS,EC2,eu-central-2,eu-central-2,Europe,True,Available
19,AWS,EC2,eu-north-1,eu-north-1,Europe,True,Available
20,AWS,EC2,eu-south-1,eu-south-1,Europe,True,Available
21,AWS,EC2,eu-south-2,eu-south-2,Europe,True,Available
22,AWS,EC2,eu-west-1,eu-west-1,Europe,True,Available
23,AWS,EC2,eu-west-2,eu-west-2,Europe,True,Available
24,AWS,EC2,eu-west-3,eu-west-3,Europe,True,Available
25,AWS,EC2,il-central-1,il-central-1,Middle East,True,Available
26,AWS,EC2,me-central-1,me-central-1,Middle East,True,Available
27,AWS,EC2,me-south-1,me-south-1,Middle East,True,Available
28,AWS,EC2,mx-central-1,mx-central-1,North America,True,Available
29,AWS,EC2,sa-east-1,sa-east-1,South America,True,Available
30,AWS,EC2,us-east-1,us-east-1,North America,True,Available
31,AWS,EC2,us-east-2,us-east-2,North America,True,Available
32,AWS,EC2,us-west-1,us-west-1,North America,True,Available
33,AWS,EC2,us-west-2,us-west-2,North America,True,Available
34,Azure,Cloud Platform,eastus,East US,North America,True,Available
35,Azure,Cloud Platform,eastus2,East US 2,North America,True,Available
36,Azure,Cloud Platform,centralus,Central US,North America,True,Available
37,Azure,Cloud Platform,westus,West US,North America,True,Available
38,Azure,Cloud Platform,westus2,West US 2,North America,True,Available
39,Azure,Cloud Platform,canadacentral,Canada Central,North America,True,Available
40,Azure,Cloud Platform,brazilsouth,Brazil South,South America,True,Available
41,Azure,Cloud Platform,uksouth,UK South,Europe,True,Available
42,Azure,Cloud Platform,francecentral,France Central,Europe,True,Available
43,Azure,Cloud Platform,germanywestcentral,Germany West Central,Europe,True,Available
44,Azure,Cloud Platform,japaneast,Japan East,Asia Pacific,True,Available
45,Azure,Cloud Platform,koreacentral,Korea Central,Asia Pacific,True,Available
46,Azure,Cloud Platform,southeastasia,Southeast Asia,Asia Pacific,True,Available
47,Azure,Cloud Platform,australiaeast,Australia East,Oceania,True,Available
48,Azure,Cloud Platform,uaenorth,UAE North,Middle East,True,Available
49,Azure,Cloud Platform,southafricanorth,South Africa North,Africa,True,Available
50,GCP,Cloud Platform,us-central1,us-central1 (Iowa),North America,True,Available
51,GCP,Cloud Platform,us-east1,us-east1 (South Carolina),North America,True,Available
52,GCP,Cloud Platform,us-east4,us-east4 (Northern Virginia),North America,True,Available
53,GCP,Cloud Platform,us-west1,us-west1 (Oregon),North America,True,Available
54,GCP,Cloud Platform,northamerica-northeast1,northamerica-northeast1 (Montreal),North America,True,Available
55,GCP,Cloud Platform,europe-west1,europe-west1 (Belgium),Europe,True,Available
56,GCP,Cloud Platform,asia-east1,asia-east1 (Taiwan),Asia Pacific,True,Available

In [29]:
multi_cloud_df.groupby("provider").size()

provider
AWS      34
Azure    16
GCP       7
dtype: int64

In [30]:
multi_cloud_df.groupby(["provider", "continent"]).size()

provider  continent
AWS       Africa            1
          Asia Pacific     14
          Europe            8
          Middle East       3
          North America     7
          South America     1
Azure     Africa            1
          Asia Pacific      3
          Europe            3
          Middle East       1
          North America     6
          Oceania           1
          South America     1
GCP       Asia Pacific      1
          Europe            1
          North America     5
dtype: int64

In [31]:
multi_cloud_df["continent"].value_counts()

continent
Asia Pacific     18
North America    18
Europe           12
Middle East       4
Africa            2
South America     2
Oceania           1
Name: count, dtype: int64