In [1]:
from pathlib import Path
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
from datetime import date

RAW_DIR = Path("raw_data")
CURATED_DIR = Path("curated_data")

RAW_DIR.mkdir(exist_ok=True)
CURATED_DIR.mkdir(exist_ok=True)

COLLECTION_DATE = date.today().isoformat()

print("Folders ready")
print("Collection date:", COLLECTION_DATE)

Folders ready
Collection date: 2026-06-04

In [2]:
headers = {
    "User-Agent": "Mozilla/5.0"
}

def get_soup(url):
    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")

def clean_text(text):
    if pd.isna(text):
        return None
    text = re.sub(r"\s+", " ", str(text)).strip()
    return text

In [3]:
aws_url = "https://aws.amazon.com/products/"
aws_soup = get_soup(aws_url)

aws_text = aws_soup.get_text("\n")

with open(RAW_DIR / "aws_products_page_raw.txt", "w", encoding="utf-8") as f:
    f.write(aws_text)

print("AWS page downloaded")
print(aws_text[:1000])

AWS page downloaded


























Cloud Services - Build and Scale Securely- AWS






































































































































































Skip to main content

































































































































































Filter: All























































































English












Contact us


AWS Marketplace




Support















My account












































































Search


























































































Filter: All













































Sign in to console




Create account






















































































Home










Cloud Se

In [4]:
aws_links = []

for a in aws_soup.find_all("a", href=True):
    text = clean_text(a.get_text())
    href = a["href"]

    if text and href:
        aws_links.append({
            "text": text,
            "href": href
        })

aws_links_df = pd.DataFrame(aws_links).drop_duplicates()

aws_links_df.head(50)

,text,href
0,Skip to main content,#aws-page-content-main
1,Contact us,/contact-us/?nc2=h_ut_cu
2,AWS Marketplace,https://aws.amazon.com/marketplace?nc2=h_utmp
3,Sign in to console,https://console.aws.amazon.com/console/home/?n...
4,Create account,https://signin.aws.amazon.com/signup?request_t...
5,Home,/
6,Learn more about AWS Regions,/about-aws/global-infrastructure/?hp=tile&tile...
7,Resources Read what top analysts such as Gartn...,/resources/analyst-reports/?sc_icampaign=aware...
8,Training On-demand resources to help you devel...,/training/?sc_icampaign=aware_aws-training&sc_...
9,Partners Join AWS Partner Network to build and...,/partners/?sc_icampaign=aware_apn_recruit&sc_i...
10,Marketplace Launch a variety of popular softwa...,https://aws.amazon.com/marketplace?sc_icampaig...
11,Announcements Stay informed about upcoming ser...,https://docs.aws.amazon.com/general/latest/gr/...
12,Create an AWS account,https://signin.aws.amazon.com/signup?request_t...
13,What Is AWS?,/what-is-aws/?nc1=f_cc
14,What Is Cloud Computing?,/what-is-cloud-computing/?nc1=f_cc
15,What Is Agentic AI?,/what-is/agentic-ai/?nc1=f_cc
16,Cloud Computing Concepts Hub,/what-is/?nc1=f_cc
17,AWS Cloud Security,/security/?nc1=f_cc
18,What's New,/new/?nc1=f_cc
19,Blogs,/blogs/?nc1=f_cc
20,Press Releases,https://press.aboutamazon.com/press-releases/aws
21,Getting Started,/getting-started/?nc1=f_cc
22,Training,/training/?nc1=f_cc
23,AWS Trust Center,/trust-center/?nc1=f_cc
24,AWS Solutions Library,/solutions/?nc1=f_cc
25,Architecture Center,/architecture/?nc1=f_cc
26,Product and Technical FAQs,/faqs/?nc1=f_dr
27,Analyst Reports,/resources/analyst-reports/?nc1=f_cc
28,AWS Partners,/partners/work-with-partners/?nc1=f_dr
29,Builder Center,/developer/?nc1=f_dr
30,SDKs & Tools,/developer/tools/?nc1=f_dr
31,.NET on AWS,/developer/language/net/?nc1=f_dr
32,Python on AWS,/developer/language/python/?nc1=f_dr
33,Java on AWS,/developer/language/java/?nc1=f_dr
34,PHP on AWS,/developer/language/php/?nc1=f_cc
35,JavaScript on AWS,/developer/language/javascript/?nc1=f_dr
36,Contact Us,/contact-us/?nc1=f_m
37,File a Support Ticket,https://console.aws.amazon.com/support/home/?n...
38,AWS re:Post,https://repost.aws/?nc1=f_dr
39,Knowledge Center,https://repost.aws/knowledge-center/?nc1=f_dr
40,AWS Support Overview,/premiumsupport/?nc1=f_dr
41,Get Expert Help,https://iq.aws.amazon.com/?utm=mkt.foot/?nc1=f_m
42,AWS Accessibility,/accessibility/?nc1=f_cc
43,Legal,/legal/?nc1=f_cc
44,Event Code of Conduct,/codeofconduct/?nc1=f_cc
45,Event Terms & Conditions,/events/terms/?nc1=f_cc
46,x,https://twitter.com/awscloud
47,facebook,https://www.facebook.com/amazonwebservices
48,linkedin,https://www.linkedin.com/company/amazon-web-se...
49,instagram,https://www.instagram.com/amazonwebservices/

In [5]:
aws_service_links = aws_links_df[
    aws_links_df["href"].str.contains("/products/|/what-is/|/s3/|/ec2/|/lambda/|/rds/|/sagemaker/|/bedrock/", case=False, na=False)
].copy()

aws_service_links = aws_service_links[
    ~aws_service_links["text"].str.contains(
        "Sign in|Create account|Contact us|Support|Marketplace|English|Learn more|Documentation",
        case=False,
        na=False
    )
]

aws_service_links = aws_service_links.drop_duplicates(subset=["text"])

aws_service_links.head(100)

                            text                           href
15           What Is Agentic AI?  /what-is/agentic-ai/?nc1=f_cc
16  Cloud Computing Concepts Hub             /what-is/?nc1=f_cc

In [6]:
aws_service_links.to_csv(
    RAW_DIR / "aws_service_links_candidate.csv",
    index=False
)

print("Candidate AWS links:", len(aws_service_links))
aws_service_links[["text", "href"]].head(100)

Candidate AWS links: 2

                            text                           href
15           What Is Agentic AI?  /what-is/agentic-ai/?nc1=f_cc
16  Cloud Computing Concepts Hub             /what-is/?nc1=f_cc

In [7]:
import pandas as pd

native = pd.read_csv("native_cloud_service_catalog.csv")

aws = native[native["provider"]=="AWS"]

print("AWS services:", len(aws))

aws["service_name"].sort_values().tolist()[:100]

AWS services: 69

['AMSOperations',
 'AWSBackup',
 'AWSBillingConductor',
 'AWSCloudTrail',
 'AWSCodeArtifact',
 'AWSCodePipeline',
 'AWSComputeOptimizer',
 'AWSDatabaseMigrationSvc',
 'AWSDeveloperSupport',
 'AWSElementalMediaTailor',
 'AWSEndUserMessaging3pFees',
 'AWSEvents',
 'AWSIAMAccessAnalyzer',
 'AWSInterconnect',
 'AWSIoTAnalytics',
 'AWSIoTEvents',
 'AWSLambda',
 'AWSNetworkFirewall',
 'AWSQueueService',
 'AWSSecurityHub',
 'AWSSecurityIncidentResponse',
 'AWSStorageGateway',
 'AWSStorageGatewayDeepArchive',
 'AWSSupplyChain',
 'AWSSupportBusiness',
 'AWSSupportEnterprise',
 'AWSSupportEssential',
 'AWSTelcoNetworkBuilder',
 'AWSUnifiedOperations',
 'AmazonApiGateway',
 'AmazonAthena',
 'AmazonBedrock',
 'AmazonBedrockAgentCore',
 'AmazonBedrockFoundationModels',
 'AmazonBedrockService',
 'AmazonDevOpsGuru',
 'AmazonDynamoDB',
 'AmazonEC2',
 'AmazonEC2OCPULicenseFees',
 'AmazonECS',
 'AmazonEFS',
 'AmazonEKS',
 'AmazonEKSAnywhere',
 'AmazonFSx',
 'AmazonGuardDuty',
 'AmazonKinesis',
 'AmazonKinesisAnalytics',
 'AmazonKinesisFirehose',
 'AmazonKinesisVideo',
 'AmazonLightsail',
 'AmazonLookoutVision',
 'AmazonML',
 'AmazonManagedBlockchain',
 'AmazonRedshift',
 'AmazonS3GlacierDeepArchive',
 'AmazonSNS',
 'AmazonSageMaker',
 'AmazonSecurityLake',
 'AmazonVPC',
 'AmazonWorkMail',
 'AuroraDSQL',
 'CodeBuild',
 'DevOpsAgent',
 'IoTDeviceDefender',
 'IoTDeviceManagement',
 'VMwareCloudOnAWS',
 'awskms',
 'mobileanalytics',
 'translate']

In [8]:
aws.groupby("category").size().sort_values(ascending=False)

category
AI / Machine Learning      14
Analytics                   8
Compute                     8
Security                    7
Storage                     6
Billing / Support           5
DevOps                      5
Networking                  5
Messaging / Integration     5
Management                  3
Database                    3
dtype: int64

In [9]:
native = pd.read_csv("native_cloud_service_catalog.csv")

azure = native[native["provider"]=="Azure"]

print("Azure services:", len(azure))

azure["service_name"].sort_values().tolist()

Azure services: 32

['Application Gateway',
 'Archive Storage',
 'Azure AI Search',
 'Azure AI Services',
 'Azure Automation',
 'Azure CDN',
 'Azure Cache for Redis',
 'Azure Container Instances',
 'Azure DNS',
 'Azure Database for MySQL',
 'Azure Database for PostgreSQL',
 'Azure Firewall',
 'Azure Functions',
 'Azure Kubernetes Service',
 'Azure Machine Learning',
 'Azure Monitor',
 'Azure OpenAI Service',
 'Azure Policy',
 'Azure Resource Manager',
 'Azure SQL Database',
 'Azure Stream Analytics',
 'Azure Synapse Analytics',
 'Blob Storage',
 'Data Lake Storage',
 'Disk Storage',
 'Load Balancer',
 'Microsoft Defender for Cloud',
 'Microsoft Sentinel',
 'Queue Storage',
 'VPN Gateway',
 'Virtual Machines',
 'Virtual Network']

In [10]:
gcp = native[native["provider"]=="GCP"]

print("GCP services:", len(gcp))

gcp["service_name"].sort_values().tolist()[:100]

GCP services: 359

[' Secured Postgresql on Windows 2012 R2',
 'AI/ML development, training & inference using Python & Jupyter',
 'AISE PyTorch CPU Production',
 'AISE PyTorch NVidia GPU Production',
 'AISE TensorFlow NVidia GPU Production',
 'APEX Protection Storage for Google (DDVE)',
 'API Gateway',
 'AXI AI Forecast ML',
 'AXI AI SAP EasyConnect',
 'AXI AI SAP EasyConnect Plus',
 'Abzooba Inc. xpresso-ai',
 'Accelerated Joomla',
 'Active Directory Domain Controller 2016',
 'Active Directory Domain Controller 2019',
 'Airlock Gateway 7.4',
 'Airlock Gateway 7.5',
 'Airlock Gateway 7.6',
 'Airlock Gateway 7.7',
 'Airtable',
 'Aiven Platform: Managed Database and Data Streaming Services',
 'Aiven for Apache Cassandra',
 'Aiven for Apache Kafka',
 'Aiven for Apache Kafka Connect',
 'Aiven for Apache Kafka MirrorMaker 2',
 'Aiven for MySQL',
 'Aiven for PostgreSQL',
 'Aiven for Redis',
 'Anthos Policy Controller',
 'Aparavi Aparavi Active Archive',
 'App Engine',
 'Aqua Cloud Native Security Platform',
 'Aqua Enterprise Security Platform',
 'Arista Networks Inc. cloudeos-router-payg',
 'Array Networks vAPV - BYOL',
 'Artifact Registry',
 'AtScale Inc AtScale Adaptive Analytics',
 'AtomicWP Cloud Workload Security',
 'AtomicWP Cloud Workload Security for Docker',
 'Atos Database hotel for GCP',
 'AutoML Neuton',
 'Aviatrix Cloud Network CoPilot',
 'Aviatrix Cloud Network Controller',
 'Backup and DR Service',
 'Backup for GKE',
 'Barracuda CloudGen Firewall (BYOL)',
 'BeyondInsight (SQL-Free)',
 'BigQuery',
 'BigQuery BI Engine',
 'BigQuery Data Transfer Service',
 'BigQuery Reservation API',
 'BigQuery Storage API',
 'BizStats AI',
 'Blockchain Accelerator',
 'Blockchain Solution Platform',
 'BlueCat DNS for Google Cloud Platform',
 'Cavirin First Line of Defense for Cloud Security - BYOL',
 'Check Point CloudGuard Network Security Autoscaling (BYOL)',
 'Check Point CloudGuard Network Security High Availability (BYOL)',
 'Cisco ASA virtual firewall (ASAv)',
 'Cisco Firepower Management Center (FMCv) BYOL',
 'Cisco Firepower NGFW virtual firewall (NGFWv)',
 'Cisco Meraki vMX',
 'Click to Deploy VM Deployment for Redis',
 'Cloud AutoML',
 'Cloud Bigtable',
 'Cloud Build',
 'Cloud Contact Center AI Platform',
 'Cloud DNS',
 'Cloud Data Loss Prevention',
 'Cloud Dataflow',
 'Cloud Document AI API',
 'Cloud Domains',
 'Cloud KMS KACLS',
 'Cloud Key Management Service (KMS)',
 'Cloud Logging',
 'Cloud Machine Learning Engine',
 'Cloud Memorystore for Redis',
 'Cloud Monitoring',
 'Cloud Pub/Sub',
 'Cloud Run',
 'Cloud Run Functions',
 'Cloud SQL',
 'Cloud Security Connector for Zscaler (ZIA)',
 'Cloud Spanner',
 'Cloud Speech API',
 'Cloud Storage',
 'Cloud Text-to-Speech API',
 'Cloud Vision API',
 'Cloud Vision OCR On-Prem',
 'CloudBees Jenkins Distribution',
 'CloudBees Jenkins Support',
 'CloudGuard Network Security NGFW and Threat Prevention (BYOL)',
 'Cloudinary Dynamic Media Management Solution',
 'Cloudup Joomla  on Debian 9',
 'Cohesity Backup as a Service',
 'Commvault Backup & Recovery  BYOL',
 'CompilerWorks compilerworks-vm deployment',
 'Compute Engine',
 'Container Registry Vulnerability Scanning',
 'Corezoid Hyperautomation Engine']

In [11]:
import pandas as pd

native = pd.read_csv("native_cloud_service_catalog.csv")

gcp = native[native["provider"]=="GCP"].copy()

marketplace_keywords = [
    "Cisco",
    "Fortinet",
    "Forti",
    "Aiven",
    "Jenkins",
    "CloudBees",
    "MediaWiki",
    "Airtable",
    "Aqua",
    "Barracuda",
    "BlueCat",
    "Check Point",
    "Commvault",
    "Cohesity",
    "DataStax",
    "CloudGuard",
    "VMware",
    "Redis VM",
    "Domain Controller",
    "BYOL"
]

In [12]:
pattern = "|".join(marketplace_keywords)

gcp_native = gcp[
    ~gcp["service_name"].str.contains(
        pattern,
        case=False,
        na=False
    )
].copy()

print("Original GCP:", len(gcp))
print("Clean GCP:", len(gcp_native))

Original GCP: 359
Clean GCP: 293

In [13]:
aws = native[native["provider"]=="AWS"]
azure = native[native["provider"]=="Azure"]

native_v2 = pd.concat(
    [
        aws,
        azure,
        gcp_native
    ],
    ignore_index=True
)

native_v2.to_csv(
    "curated_data/native_cloud_service_catalog_v2.csv",
    index=False
)

native_v2.groupby("provider")["service_name"].nunique()

provider
AWS       69
Azure     32
GCP      287
Name: service_name, dtype: int64

In [14]:
native_v2.groupby("provider")["service_name"].nunique()

provider
AWS       69
Azure     32
GCP      287
Name: service_name, dtype: int64

In [15]:
gcp_native["service_name"].sort_values().tolist()[:200]

[' Secured Postgresql on Windows 2012 R2',
 'AI/ML development, training & inference using Python & Jupyter',
 'AISE PyTorch CPU Production',
 'AISE PyTorch NVidia GPU Production',
 'AISE TensorFlow NVidia GPU Production',
 'APEX Protection Storage for Google (DDVE)',
 'API Gateway',
 'AXI AI Forecast ML',
 'AXI AI SAP EasyConnect',
 'AXI AI SAP EasyConnect Plus',
 'Abzooba Inc. xpresso-ai',
 'Accelerated Joomla',
 'Airlock Gateway 7.4',
 'Airlock Gateway 7.5',
 'Airlock Gateway 7.6',
 'Airlock Gateway 7.7',
 'Anthos Policy Controller',
 'Aparavi Aparavi Active Archive',
 'App Engine',
 'Arista Networks Inc. cloudeos-router-payg',
 'Artifact Registry',
 'AtScale Inc AtScale Adaptive Analytics',
 'AtomicWP Cloud Workload Security',
 'AtomicWP Cloud Workload Security for Docker',
 'Atos Database hotel for GCP',
 'AutoML Neuton',
 'Aviatrix Cloud Network CoPilot',
 'Aviatrix Cloud Network Controller',
 'Backup and DR Service',
 'Backup for GKE',
 'BeyondInsight (SQL-Free)',
 'BigQuery',
 'BigQuery BI Engine',
 'BigQuery Data Transfer Service',
 'BigQuery Reservation API',
 'BigQuery Storage API',
 'BizStats AI',
 'Blockchain Accelerator',
 'Blockchain Solution Platform',
 'Click to Deploy VM Deployment for Redis',
 'Cloud AutoML',
 'Cloud Bigtable',
 'Cloud Build',
 'Cloud Contact Center AI Platform',
 'Cloud DNS',
 'Cloud Data Loss Prevention',
 'Cloud Dataflow',
 'Cloud Document AI API',
 'Cloud Domains',
 'Cloud KMS KACLS',
 'Cloud Key Management Service (KMS)',
 'Cloud Logging',
 'Cloud Machine Learning Engine',
 'Cloud Memorystore for Redis',
 'Cloud Monitoring',
 'Cloud Pub/Sub',
 'Cloud Run',
 'Cloud Run Functions',
 'Cloud SQL',
 'Cloud Security Connector for Zscaler (ZIA)',
 'Cloud Spanner',
 'Cloud Speech API',
 'Cloud Storage',
 'Cloud Text-to-Speech API',
 'Cloud Vision API',
 'Cloud Vision OCR On-Prem',
 'Cloudinary Dynamic Media Management Solution',
 'Cloudup Joomla  on Debian 9',
 'CompilerWorks compilerworks-vm deployment',
 'Compute Engine',
 'Container Registry Vulnerability Scanning',
 'Corezoid Hyperautomation Engine',
 'Cortex Certifai',
 'Couchbase Sync Gateway',
 'CubeBackup for Google Workspace (Windows)',
 'CubeBackup-for-Docker',
 'Dace IT d/b/a Sense Traffic Pulse ORIGAMI | Oak Ridge Graph Analytics for Medical Innovation',
 'Dace IT℠with Intel OpenVINO™ Intelligent Traffic Management 2021',
 'Dace IT℠with Sense Traffic Pulse™ Smart Stadium Reference VM',
 'Dace IT℠with Sense Traffic Pulse™ and Vertex AI',
 'Data360 Analyze - Hourly Paid',
 'DataSunrise Database Security, Data Masking and Compliance',
 'Database Migration',
 'Dataiku Get Started',
 'Dataproc',
 'Dataproc Metastore',
 'Deep Learning VM',
 'Delphix DevOps Data Platform for Google Cloud Platform (3TB)',
 'Digital Asset Management',
 'DiscrimiNAT Firewall',
 'Duet AI',
 'Dynamic AI Demo',
 'Education ML',
 'End-to-end Testing Kubernetes test solution',
 'End-to-end Testing dm-solution-with-support',
 'EnterpriseDB EDB Postgres Enterprise',
 'Eventarc',
 'Evidian IDaaS (Identity as a Service)',
 'Evidian IDaaS (Identity as a Service)',
 'Exasol Analytics Database PAYG',
 'Eyeblue Cloud Storage',
 'F5 Networks F5 Advanced WAF  (PAYG, 1Gbps)',
 'F5 Networks F5 Advanced WAF  (PAYG, 200Mbps)',
 'F5 Networks F5 Advanced WAF  (PAYG, 25Mbps)',
 'F5 Networks F5 Advanced WAF (PAYG, 16vCPU)',
 'F5 Networks F5 Advanced WAF (PAYG, 8vCPU)',
 'F5 Networks F5 Per-App VE  Advanced WAF  (PAYG, 200Mbps)',
 'F5 Networks F5 Per-App VE  Advanced WAF  (PAYG, 25Mbps)',
 'F5 Networks F5 Per-App VE  BIG-IP LTM  (PAYG, 200Mbps)',
 'F5 Networks F5 Per-App VE  BIG-IP LTM  (PAYG, 25Mbps)',
 'F5 Networks F5 Per-App VE - Advanced WAF + LTM (PAYG, 200M)',
 'F5 Networks F5 Per-App VE - Advanced WAF + LTM (PAYG, 25M)',
 'Firebase Realtime Database',
 'FlashGrid Cluster for Oracle RAC / SI Database (OL7)',
 'FlashGrid Cluster for Oracle RAC / SI Database (OL8)',
 'FlashGrid Cluster for Oracle RAC / SI Database (RH7)',
 'FlashGrid Cluster for Oracle RAC / SI Database (RH8)',
 'GithubCE-v2-9-0',
 'Google Click to Deploy Migrate for Compute Engine (formerly Velostrata)',
 'Google Maps Platform Air Quality Service',
 'Google Quickstart Simple pre-configured Debian VM',
 'Healthcare ML',
 'HeidiSQL on Windows 2012 R2',
 'Identity Platform',
 'Informatica Intelligent Data Management Cloud Secure Agent',
 'Instana - Container & Microservices Monitoring on GCP',
 'Intelligent Video Analytics VM',
 'Ionic Security, Inc. Ionic Machina',
 'Iron Mountain InSight®',
 'JFrog DevOps Platform - Enterprise X',
 'JFrog DevOps Platform - Enterprise+',
 'JFrog DevOps Platform - Pro - 30 Day Free Trial',
 'JFrog Enterprise - Secure DevOps Platform - Test',
 'JFrog Test - JFrog Enterprise+ (Complete DevOps Platform) -Test',
 'JOOMLA',
 'Joomla on Windows 2012 R2',
 'Joomla!',
 'Kubernetes Cost Attribution',
 'Kubernetes Engine',
 'LABS.AI E.D.D.I - Open Source Chatbot Platform',
 'LABS.AI E.D.D.I - Open Source Chatbot Platform',
 'Lacework, Inc. Lacework Cloud Security Platform',
 'Load Balancer ADC Enterprise GCP',
 'LogicMonitor',
 'Logistic ML',
 'MariaDB Managed Database',
 'Marketing ML',
 'Mautic: The Ultimate Marketing Automation Platform',
 'Mautic: The Ultimate Marketing Automation Platform',
 'MayaData Cloud File Gateway',
 'MayaNAS Cloud File Storage',
 'MayaScale Composable NVMe Disaggregate Shared Storage ',
 'Microfusion Technology Co., Ltd AmigoCDN',
 'MinIO Object Storage',
 'Modshield SB - Web Application Firewall',
 'Money Saver VM',
 'Moodle: The Ultimate Learning Management System',
 'Moodle: The Ultimate Learning Management System',
 'Multiuser Python Jupyter notebook for AI/ML',
 'MySQL',
 'MySQL 5.6 on Windows 2012 R2',
 'MySQL 5.7',
 'MySQL 5.7 on Windows 2012 R2',
 'MySQL 8 (Codelab)',
 'MySQL Secured by SG',
 'MySQL with IIS on Windows 2012 R2',
 'NETSCOUT Application Performance Management for GCP',
 'NETSCOUT Application Performance Management for GCP - nGeniusONE',
 'NETSCOUT Application Performance Management for GCP - vSTREAM',
 'NVIDIA Clara Train SDK on Google Cloud',
 'NVIDIA GPU-Optimized TensorFlow VMI',
 'NVIDIA GPU-Optimized VMI',
 'NVIDIA Image for AI using GPUs',
 'NVIDIA Image for AI using GPUs - Optimized for PyTorch',
 'NVIDIA Image for AI using GPUs - Optimized for TensorFlow',
 'NetFoundry Inc. NetFoundry Zero Trust Networking Platform',
 'NetScaler Web App Firewall (WAF) - 1000 Mbps',
 'Netsil - Application Operations Center (Self-Hosted)',
 'Network Connectivity Center',
 'Network Security',
 'Networking',
 'Open Source Social Network',
 'OpenLogic CentOS 7.8 (v20200922) - Security Hardened',
 'OpenLogic CentOS 7.9 (v20201130) - Security Hardened',
 'OpenVINO™ Toolkit Smart City Reference Implementation VM',
 'OrangeHRM-The Ultimate HR Management Solution',
 'OrchardCMS: The Ultimate Content Management System',
 'OrchardCMS: The Ultimate Content Management System',
 'OroCommerce VM',
 'PREDICTIVE ANALYTICS FRAMEWORK R HADOOP',
 'Payment Gateway',
 'PerimeterX Bot Defender Mobile',
 'PerimeterX Bot Defender Web',
 'PerimeterX Code Defender',
 'Pivotal Software, Inc. Pivotal Postgres',
 'Piwigo Gallery: Your Personalized Photo Management Solution',
 'PostgreSQL',
 'PostgreSQL 9.6',
 'PostgreSQL Cluster (with Bucardo replication)',
 'PostgreSQL with CentOS 8.3']

In [16]:
services = sorted(gcp_native["service_name"].unique())

for s in services[:200]:
    print(s)

 Secured Postgresql on Windows 2012 R2
AI/ML development, training & inference using Python & Jupyter
AISE PyTorch CPU Production
AISE PyTorch NVidia GPU Production
AISE TensorFlow NVidia GPU Production
APEX Protection Storage for Google (DDVE)
API Gateway
AXI AI Forecast ML
AXI AI SAP EasyConnect
AXI AI SAP EasyConnect Plus
Abzooba Inc. xpresso-ai
Accelerated Joomla
Airlock Gateway 7.4
Airlock Gateway 7.5
Airlock Gateway 7.6
Airlock Gateway 7.7
Anthos Policy Controller
Aparavi Aparavi Active Archive
App Engine
Arista Networks Inc. cloudeos-router-payg
Artifact Registry
AtScale Inc AtScale Adaptive Analytics
AtomicWP Cloud Workload Security
AtomicWP Cloud Workload Security for Docker
Atos Database hotel for GCP
AutoML Neuton
Aviatrix Cloud Network CoPilot
Aviatrix Cloud Network Controller
Backup and DR Service
Backup for GKE
BeyondInsight (SQL-Free)
BigQuery
BigQuery BI Engine
BigQuery Data Transfer Service
BigQuery Reservation API
BigQuery Storage API
BizStats AI
Blockchain Accelerator
Blockchain Solution Platform
Click to Deploy VM Deployment for Redis
Cloud AutoML
Cloud Bigtable
Cloud Build
Cloud Contact Center AI Platform
Cloud DNS
Cloud Data Loss Prevention
Cloud Dataflow
Cloud Document AI API
Cloud Domains
Cloud KMS KACLS
Cloud Key Management Service (KMS)
Cloud Logging
Cloud Machine Learning Engine
Cloud Memorystore for Redis
Cloud Monitoring
Cloud Pub/Sub
Cloud Run
Cloud Run Functions
Cloud SQL
Cloud Security Connector for Zscaler (ZIA)
Cloud Spanner
Cloud Speech API
Cloud Storage
Cloud Text-to-Speech API
Cloud Vision API
Cloud Vision OCR On-Prem
Cloudinary Dynamic Media Management Solution
Cloudup Joomla  on Debian 9
CompilerWorks compilerworks-vm deployment
Compute Engine
Container Registry Vulnerability Scanning
Corezoid Hyperautomation Engine
Cortex Certifai
Couchbase Sync Gateway
CubeBackup for Google Workspace (Windows)
CubeBackup-for-Docker
Dace IT d/b/a Sense Traffic Pulse ORIGAMI | Oak Ridge Graph Analytics for Medical Innovation
Dace IT℠with Intel OpenVINO™ Intelligent Traffic Management 2021
Dace IT℠with Sense Traffic Pulse™ Smart Stadium Reference VM
Dace IT℠with Sense Traffic Pulse™ and Vertex AI
Data360 Analyze - Hourly Paid
DataSunrise Database Security, Data Masking and Compliance
Database Migration
Dataiku Get Started
Dataproc
Dataproc Metastore
Deep Learning VM
Delphix DevOps Data Platform for Google Cloud Platform (3TB)
Digital Asset Management
DiscrimiNAT Firewall
Duet AI
Dynamic AI Demo
Education ML
End-to-end Testing Kubernetes test solution
End-to-end Testing dm-solution-with-support
EnterpriseDB EDB Postgres Enterprise
Eventarc
Evidian IDaaS (Identity as a Service)
Exasol Analytics Database PAYG
Eyeblue Cloud Storage
F5 Networks F5 Advanced WAF  (PAYG, 1Gbps)
F5 Networks F5 Advanced WAF  (PAYG, 200Mbps)
F5 Networks F5 Advanced WAF  (PAYG, 25Mbps)
F5 Networks F5 Advanced WAF (PAYG, 16vCPU)
F5 Networks F5 Advanced WAF (PAYG, 8vCPU)
F5 Networks F5 Per-App VE  Advanced WAF  (PAYG, 200Mbps)
F5 Networks F5 Per-App VE  Advanced WAF  (PAYG, 25Mbps)
F5 Networks F5 Per-App VE  BIG-IP LTM  (PAYG, 200Mbps)
F5 Networks F5 Per-App VE  BIG-IP LTM  (PAYG, 25Mbps)
F5 Networks F5 Per-App VE - Advanced WAF + LTM (PAYG, 200M)
F5 Networks F5 Per-App VE - Advanced WAF + LTM (PAYG, 25M)
Firebase Realtime Database
FlashGrid Cluster for Oracle RAC / SI Database (OL7)
FlashGrid Cluster for Oracle RAC / SI Database (OL8)
FlashGrid Cluster for Oracle RAC / SI Database (RH7)
FlashGrid Cluster for Oracle RAC / SI Database (RH8)
GithubCE-v2-9-0
Google Click to Deploy Migrate for Compute Engine (formerly Velostrata)
Google Maps Platform Air Quality Service
Google Quickstart Simple pre-configured Debian VM
Healthcare ML
HeidiSQL on Windows 2012 R2
Identity Platform
Informatica Intelligent Data Management Cloud Secure Agent
Instana - Container & Microservices Monitoring on GCP
Intelligent Video Analytics VM
Ionic Security, Inc. Ionic Machina
Iron Mountain InSight®
JFrog DevOps Platform - Enterprise X
JFrog DevOps Platform - Enterprise+
JFrog DevOps Platform - Pro - 30 Day Free Trial
JFrog Enterprise - Secure DevOps Platform - Test
JFrog Test - JFrog Enterprise+ (Complete DevOps Platform) -Test
JOOMLA
Joomla on Windows 2012 R2
Joomla!
Kubernetes Cost Attribution
Kubernetes Engine
LABS.AI E.D.D.I - Open Source Chatbot Platform
Lacework, Inc. Lacework Cloud Security Platform
Load Balancer ADC Enterprise GCP
LogicMonitor
Logistic ML
MariaDB Managed Database
Marketing ML
Mautic: The Ultimate Marketing Automation Platform
MayaData Cloud File Gateway
MayaNAS Cloud File Storage
MayaScale Composable NVMe Disaggregate Shared Storage
Microfusion Technology Co., Ltd AmigoCDN
MinIO Object Storage
Modshield SB - Web Application Firewall
Money Saver VM
Moodle: The Ultimate Learning Management System
Multiuser Python Jupyter notebook for AI/ML
MySQL
MySQL 5.6 on Windows 2012 R2
MySQL 5.7
MySQL 5.7 on Windows 2012 R2
MySQL 8 (Codelab)
MySQL Secured by SG
MySQL with IIS on Windows 2012 R2
NETSCOUT Application Performance Management for GCP
NETSCOUT Application Performance Management for GCP - nGeniusONE
NETSCOUT Application Performance Management for GCP - vSTREAM
NVIDIA Clara Train SDK on Google Cloud
NVIDIA GPU-Optimized TensorFlow VMI
NVIDIA GPU-Optimized VMI
NVIDIA Image for AI using GPUs
NVIDIA Image for AI using GPUs - Optimized for PyTorch
NVIDIA Image for AI using GPUs - Optimized for TensorFlow
NetFoundry Inc. NetFoundry Zero Trust Networking Platform
NetScaler Web App Firewall (WAF) - 1000 Mbps
Netsil - Application Operations Center (Self-Hosted)
Network Connectivity Center
Network Security
Networking
Open Source Social Network
OpenLogic CentOS 7.8 (v20200922) - Security Hardened
OpenLogic CentOS 7.9 (v20201130) - Security Hardened
OpenVINO™ Toolkit Smart City Reference Implementation VM
OrangeHRM-The Ultimate HR Management Solution
OrchardCMS: The Ultimate Content Management System
OroCommerce VM
PREDICTIVE ANALYTICS FRAMEWORK R HADOOP
Payment Gateway
PerimeterX Bot Defender Mobile
PerimeterX Bot Defender Web
PerimeterX Code Defender
Pivotal Software, Inc. Pivotal Postgres
Piwigo Gallery: Your Personalized Photo Management Solution
PostgreSQL
PostgreSQL 9.6
PostgreSQL Cluster (with Bucardo replication)
PostgreSQL with CentOS 8.3
PowerProtect DD Management Center (DDMC)
Preventive Maintenance ML
Pub/Sub Lite
QRadar Security Intelligence Platform App Host v7.3.2 P1
QRadar Security Intelligence Platform Console v7.3.2 P1

In [17]:
gcp_native_keywords = [
    "BigQuery",
    "Cloud ",
    "Compute Engine",
    "Dataproc",
    "Dataproc Metastore",
    "Artifact Registry",
    "App Engine",
    "Anthos",
    "Identity Platform",
    "Eventarc",
    "Backup for GKE",
    "Backup and DR Service",
    "Database Migration",
    "Kubernetes Engine",
    "Network Connectivity Center",
    "Network Security",
    "Pub/Sub Lite",
    "Duet AI",
    "Firebase",
    "Google Maps Platform",
]

In [18]:
pattern = "|".join(gcp_native_keywords)

gcp_official = gcp[
    gcp["service_name"].str.contains(
        pattern,
        case=False,
        na=False
    )
].copy()

print("Official GCP Services:", len(gcp_official))

Official GCP Services: 79

In [19]:
sorted(gcp_official["service_name"].unique())

['Anthos Policy Controller',
 'App Engine',
 'Aqua Cloud Native Security Platform',
 'Artifact Registry',
 'AtomicWP Cloud Workload Security',
 'AtomicWP Cloud Workload Security for Docker',
 'Aviatrix Cloud Network CoPilot',
 'Aviatrix Cloud Network Controller',
 'Backup and DR Service',
 'Backup for GKE',
 'BigQuery',
 'BigQuery BI Engine',
 'BigQuery Data Transfer Service',
 'BigQuery Reservation API',
 'BigQuery Storage API',
 'BlueCat DNS for Google Cloud Platform',
 'Cavirin First Line of Defense for Cloud Security - BYOL',
 'Check Point CloudGuard Network Security Autoscaling (BYOL)',
 'Check Point CloudGuard Network Security High Availability (BYOL)',
 'Cloud AutoML',
 'Cloud Bigtable',
 'Cloud Build',
 'Cloud Contact Center AI Platform',
 'Cloud DNS',
 'Cloud Data Loss Prevention',
 'Cloud Dataflow',
 'Cloud Document AI API',
 'Cloud Domains',
 'Cloud KMS KACLS',
 'Cloud Key Management Service (KMS)',
 'Cloud Logging',
 'Cloud Machine Learning Engine',
 'Cloud Memorystore for Redis',
 'Cloud Monitoring',
 'Cloud Pub/Sub',
 'Cloud Run',
 'Cloud Run Functions',
 'Cloud SQL',
 'Cloud Security Connector for Zscaler (ZIA)',
 'Cloud Spanner',
 'Cloud Speech API',
 'Cloud Storage',
 'Cloud Text-to-Speech API',
 'Cloud Vision API',
 'Cloud Vision OCR On-Prem',
 'CloudGuard Network Security NGFW and Threat Prevention (BYOL)',
 'Compute Engine',
 'Database Migration',
 'Dataproc',
 'Dataproc Metastore',
 'Delphix DevOps Data Platform for Google Cloud Platform (3TB)',
 'Duet AI',
 'Eventarc',
 'Eyeblue Cloud Storage',
 'Firebase Realtime Database',
 'Google Click to Deploy Migrate for Compute Engine (formerly Velostrata)',
 'Google Maps Platform Air Quality Service',
 'Identity Platform',
 'Informatica Intelligent Data Management Cloud Secure Agent',
 'Kaspersky Hybrid Cloud Security (BYOL)',
 'Kubernetes Engine',
 'Lacework, Inc. Lacework Cloud Security Platform',
 'MayaData Cloud File Gateway',
 'MayaNAS Cloud File Storage',
 'Network Connectivity Center',
 'Network Security',
 'Pub/Sub Lite',
 'Qtum Chain Foundation Unita compute engine',
 'Rakuten Symphony Symcloud Storage',
 'Real-Time Data Integration to BigQuery',
 'Real-Time Data Integration to Google Cloud Storage',
 'Real-Time Integration to Cloud SQL for MySQL',
 'Real-Time Integration to Cloud SQL for PostgreSQL',
 'Real-Time Integration to Cloud Spanner',
 'Sense Traffic Pulse™ and Cloud AutoML',
 'Striim Inc. Striim for Google Database Migration',
 'Unravel for Dataproc',
 'itopia Cloud Automation Stack',
 'superQuery for BigQuery']

In [20]:
official_gcp_services = [
    "Anthos Policy Controller",
    "App Engine",
    "Artifact Registry",
    "Backup and DR Service",
    "Backup for GKE",
    "BigQuery",
    "BigQuery BI Engine",
    "BigQuery Data Transfer Service",
    "BigQuery Reservation API",
    "BigQuery Storage API",
    "Cloud AutoML",
    "Cloud Bigtable",
    "Cloud Build",
    "Cloud Contact Center AI Platform",
    "Cloud DNS",
    "Cloud Data Loss Prevention",
    "Cloud Dataflow",
    "Cloud Document AI API",
    "Cloud Domains",
    "Cloud Key Management Service (KMS)",
    "Cloud Logging",
    "Cloud Machine Learning Engine",
    "Cloud Memorystore for Redis",
    "Cloud Monitoring",
    "Cloud Pub/Sub",
    "Cloud Run",
    "Cloud Run Functions",
    "Cloud SQL",
    "Cloud Spanner",
    "Cloud Speech API",
    "Cloud Storage",
    "Cloud Text-to-Speech API",
    "Cloud Vision API",
    "Compute Engine",
    "Database Migration",
    "Dataproc",
    "Dataproc Metastore",
    "Duet AI",
    "Eventarc",
    "Firebase Realtime Database",
    "Google Maps Platform Air Quality Service",
    "Identity Platform",
    "Kubernetes Engine",
    "Network Connectivity Center",
    "Network Security",
    "Pub/Sub Lite"
]

In [21]:
gcp_final = gcp[
    gcp["service_name"].isin(official_gcp_services)
].copy()

print("Official GCP Services:", gcp_final["service_name"].nunique())

sorted(gcp_final["service_name"].unique())

Official GCP Services: 46

['Anthos Policy Controller',
 'App Engine',
 'Artifact Registry',
 'Backup and DR Service',
 'Backup for GKE',
 'BigQuery',
 'BigQuery BI Engine',
 'BigQuery Data Transfer Service',
 'BigQuery Reservation API',
 'BigQuery Storage API',
 'Cloud AutoML',
 'Cloud Bigtable',
 'Cloud Build',
 'Cloud Contact Center AI Platform',
 'Cloud DNS',
 'Cloud Data Loss Prevention',
 'Cloud Dataflow',
 'Cloud Document AI API',
 'Cloud Domains',
 'Cloud Key Management Service (KMS)',
 'Cloud Logging',
 'Cloud Machine Learning Engine',
 'Cloud Memorystore for Redis',
 'Cloud Monitoring',
 'Cloud Pub/Sub',
 'Cloud Run',
 'Cloud Run Functions',
 'Cloud SQL',
 'Cloud Spanner',
 'Cloud Speech API',
 'Cloud Storage',
 'Cloud Text-to-Speech API',
 'Cloud Vision API',
 'Compute Engine',
 'Database Migration',
 'Dataproc',
 'Dataproc Metastore',
 'Duet AI',
 'Eventarc',
 'Firebase Realtime Database',
 'Google Maps Platform Air Quality Service',
 'Identity Platform',
 'Kubernetes Engine',
 'Network Connectivity Center',
 'Network Security',
 'Pub/Sub Lite']

In [22]:
aws = native[native["provider"]=="AWS"]
azure = native[native["provider"]=="Azure"]

native_v3 = pd.concat(
    [aws, azure, gcp_final],
    ignore_index=True
)

native_v3.to_csv(
    "curated_data/native_cloud_service_catalog_v3.csv",
    index=False
)

native_v3.groupby("provider")["service_name"].nunique()

provider
AWS      69
Azure    32
GCP      46
Name: service_name, dtype: int64

In [23]:
native_v3.groupby("provider")["service_name"].nunique()

provider
AWS      69
Azure    32
GCP      46
Name: service_name, dtype: int64

In [24]:
ai = pd.read_csv("native_ai_services_enriched.csv")

ai[[
    "provider",
    "service_name",
    "ai_type"
]]

,provider,service_name,ai_type
0,AWS,AmazonLookoutVision,Computer Vision
1,AWS,AmazonBedrockService,Foundation Models
2,AWS,AmazonSageMaker,ML Platform
3,AWS,AmazonBedrock,Foundation Models
4,AWS,AmazonBedrockAgentCore,Foundation Models
5,AWS,AmazonBedrockFoundationModels,Foundation Models
6,Azure,Azure OpenAI Service,Foundation Models
7,Azure,Azure Machine Learning,ML Platform
8,Azure,Azure AI Search,General AI
9,Azure,Azure AI Services,General AI
10,GCP,Dace IT℠with Sense Traffic Pulse™ and Vertex AI,ML Platform
11,GCP,Vertex AI Search,ML Platform
12,GCP,Cloud Contact Center AI Platform,General AI
13,GCP,Vertex AI,ML Platform
14,GCP,Cloud Document AI API,General AI
15,GCP,Cloud Machine Learning Engine,ML Platform
16,GCP,Vertex AI Vision,ML Platform

In [25]:
native_v3.to_csv(
    "curated_data/native_cloud_service_catalog_v3.csv",
    index=False
)

In [26]:
import os

os.listdir("curated_data")

['native_cloud_service_catalog_v2.csv', 'native_cloud_service_catalog_v3.csv']

In [27]:
ai = pd.read_csv("native_ai_services_enriched.csv")

ai[[
    "provider",
    "service_name",
    "ai_type"
]]

,provider,service_name,ai_type
0,AWS,AmazonLookoutVision,Computer Vision
1,AWS,AmazonBedrockService,Foundation Models
2,AWS,AmazonSageMaker,ML Platform
3,AWS,AmazonBedrock,Foundation Models
4,AWS,AmazonBedrockAgentCore,Foundation Models
5,AWS,AmazonBedrockFoundationModels,Foundation Models
6,Azure,Azure OpenAI Service,Foundation Models
7,Azure,Azure Machine Learning,ML Platform
8,Azure,Azure AI Search,General AI
9,Azure,Azure AI Services,General AI
10,GCP,Dace IT℠with Sense Traffic Pulse™ and Vertex AI,ML Platform
11,GCP,Vertex AI Search,ML Platform
12,GCP,Cloud Contact Center AI Platform,General AI
13,GCP,Vertex AI,ML Platform
14,GCP,Cloud Document AI API,General AI
15,GCP,Cloud Machine Learning Engine,ML Platform
16,GCP,Vertex AI Vision,ML Platform

In [28]:
import pandas as pd

ai = pd.read_csv("native_ai_services_enriched.csv")

# 刪除第三方
ai = ai[
    ai["service_name"] != "Dace IT℠with Sense Traffic Pulse™ and Vertex AI"
].copy()

In [29]:
taxonomy_map = {
    
    # AWS
    "AmazonBedrock":"Foundation Models",
    "AmazonBedrockService":"Foundation Models",
    "AmazonBedrockAgentCore":"AI Agents",
    "AmazonBedrockFoundationModels":"Foundation Models",
    "AmazonSageMaker":"MLOps / ML Platform",
    "AmazonLookoutVision":"Computer Vision",

    # Azure
    "Azure OpenAI Service":"Foundation Models",
    "Azure Machine Learning":"MLOps / ML Platform",
    "Azure AI Search":"Vector Search / RAG",
    "Azure AI Services":"General AI",

    # GCP
    "Vertex AI":"MLOps / ML Platform",
    "Vertex AI Search":"Vector Search / RAG",
    "Vertex AI Vision":"Computer Vision",
    "Cloud Document AI API":"Document AI",
    "Cloud Contact Center AI Platform":"Conversational AI",
    "Cloud Machine Learning Engine":"MLOps / ML Platform"
}

In [30]:
ai["ai_taxonomy"] = ai["service_name"].map(taxonomy_map)

ai[[
    "provider",
    "service_name",
    "ai_taxonomy"
]]

   provider                      service_name          ai_taxonomy
0       AWS               AmazonLookoutVision      Computer Vision
1       AWS              AmazonBedrockService    Foundation Models
2       AWS                   AmazonSageMaker  MLOps / ML Platform
3       AWS                     AmazonBedrock    Foundation Models
4       AWS            AmazonBedrockAgentCore            AI Agents
5       AWS     AmazonBedrockFoundationModels    Foundation Models
6     Azure              Azure OpenAI Service    Foundation Models
7     Azure            Azure Machine Learning  MLOps / ML Platform
8     Azure                   Azure AI Search  Vector Search / RAG
9     Azure                 Azure AI Services           General AI
11      GCP                  Vertex AI Search  Vector Search / RAG
12      GCP  Cloud Contact Center AI Platform    Conversational AI
13      GCP                         Vertex AI  MLOps / ML Platform
14      GCP             Cloud Document AI API          Document AI
15      GCP     Cloud Machine Learning Engine  MLOps / ML Platform
16      GCP                  Vertex AI Vision      Computer Vision

In [31]:
ai.groupby(
    ["provider","ai_taxonomy"]
).size()

provider  ai_taxonomy
AWS       AI Agents              1
          Computer Vision        1
          Foundation Models      3
          MLOps / ML Platform    1
Azure     Foundation Models      1
          General AI             1
          MLOps / ML Platform    1
          Vector Search / RAG    1
GCP       Computer Vision        1
          Conversational AI      1
          Document AI            1
          MLOps / ML Platform    2
          Vector Search / RAG    1
dtype: int64

In [32]:
ai_taxonomy_summary = (
    ai.groupby(
        ["provider","ai_taxonomy"]
    )
    .size()
    .reset_index(name="service_count")
)

ai_taxonomy_summary.to_csv(
    "curated_data/ai_taxonomy_summary_v2.csv",
    index=False
)

ai.to_csv(
    "curated_data/ai_services_v2.csv",
    index=False
)

ai_taxonomy_summary

   provider          ai_taxonomy  service_count
0       AWS            AI Agents              1
1       AWS      Computer Vision              1
2       AWS    Foundation Models              3
3       AWS  MLOps / ML Platform              1
4     Azure    Foundation Models              1
5     Azure           General AI              1
6     Azure  MLOps / ML Platform              1
7     Azure  Vector Search / RAG              1
8       GCP      Computer Vision              1
9       GCP    Conversational AI              1
10      GCP          Document AI              1
11      GCP  MLOps / ML Platform              2
12      GCP  Vector Search / RAG              1

In [33]:
ai_taxonomy_summary

   provider          ai_taxonomy  service_count
0       AWS            AI Agents              1
1       AWS      Computer Vision              1
2       AWS    Foundation Models              3
3       AWS  MLOps / ML Platform              1
4     Azure    Foundation Models              1
5     Azure           General AI              1
6     Azure  MLOps / ML Platform              1
7     Azure  Vector Search / RAG              1
8       GCP      Computer Vision              1
9       GCP    Conversational AI              1
10      GCP          Document AI              1
11      GCP  MLOps / ML Platform              2
12      GCP  Vector Search / RAG              1