In [1]:
import pandas as pd

df = pd.read_csv("native_cloud_service_catalog.csv")

df.head()

,provider,service_code,service_name,service_title,category,source,collection_date,category_v2,category_v3
0,AWS,VMwareCloudOnAWS,VMwareCloudOnAWS,VMwareCloudOnAWS,Compute,AWS Price List Offer Index,2026-05-28,Compute,Compute
1,AWS,AWSEndUserMessaging3pFees,AWSEndUserMessaging3pFees,AWSEndUserMessaging3pFees,Messaging / Integration,AWS Price List Offer Index,2026-05-28,Other,Other
2,AWS,AWSDatabaseMigrationSvc,AWSDatabaseMigrationSvc,AWSDatabaseMigrationSvc,Database,AWS Price List Offer Index,2026-05-28,Database,Database
3,AWS,AmazonGuardDuty,AmazonGuardDuty,AmazonGuardDuty,Security,AWS Price List Offer Index,2026-05-28,Security,Other
4,AWS,AmazonApiGateway,AmazonApiGateway,AmazonApiGateway,Networking,AWS Price List Offer Index,2026-05-28,Networking,Networking

In [2]:
ai_keywords = [
    "gpu",
    "ai",
    "machine learning",
    "ml",
    "deep learning",
    "foundation model",
    "llm",
    "training",
    "inference",
    "tensor",
    "cuda",
    "neural",
    "vision",
    "nlp",
    "generative",
    "genai",
    "bedrock",
    "vertex",
    "openai",
    "hugging face"
]

In [3]:
pattern = "|".join(ai_keywords)

ai_df = df[
    df["service_name"]
    .str.lower()
    .str.contains(pattern, na=False)
]

In [5]:
print(ai_df.shape)

ai_df[[
    "provider",
    "service_name",
    "category"
]].head(30)

(111, 9)

,provider,service_name,category
7,AWS,AmazonManagedBlockchain,AI / Machine Learning
9,AWS,AmazonLookoutVision,AI / Machine Learning
10,AWS,AmazonML,AI / Machine Learning
23,AWS,AmazonBedrockService,AI / Machine Learning
25,AWS,AWSElementalMediaTailor,AI / Machine Learning
34,AWS,AmazonWorkMail,AI / Machine Learning
51,AWS,AWSCloudTrail,AI / Machine Learning
53,AWS,AmazonLightsail,AI / Machine Learning
54,AWS,AmazonBedrock,AI / Machine Learning
57,AWS,AWSSupplyChain,AI / Machine Learning
60,AWS,AmazonBedrockAgentCore,AI / Machine Learning
61,AWS,AmazonBedrockFoundationModels,AI / Machine Learning
72,Azure,Azure Container Instances,Compute
84,Azure,Azure OpenAI Service,AI / Machine Learning
85,Azure,Azure Machine Learning,AI / Machine Learning
86,Azure,Azure AI Search,AI / Machine Learning
87,Azure,Azure AI Services,AI / Machine Learning
106,GCP,Aiven for Redis,Database
111,GCP,NVIDIA GPU-Optimized VMI,Compute
117,GCP,"AI/ML development, training & inference using ...",AI / Machine Learning
118,GCP,openlitespeed-rails,AI / Machine Learning
119,GCP,NVIDIA GPU-Optimized TensorFlow VMI,Compute
122,GCP,claire-auto-demo,AI / Machine Learning
123,GCP,Deep Learning VM,Compute
125,GCP,Weka Machine Learning on Windows 2019,AI / Machine Learning
129,GCP,Active Directory Domain Controller 2019,AI / Machine Learning
133,GCP,Airlock Gateway 7.7,AI / Machine Learning
138,GCP,Active Directory Domain Controller 2016,AI / Machine Learning
141,GCP,AISE PyTorch CPU Production,AI / Machine Learning
142,GCP,NVIDIA Image for AI using GPUs - Optimized for...,AI / Machine Learning

In [6]:
vendor_ai_count = (
    ai_df.groupby("provider")
    .size()
    .reset_index(name="ai_service_count")
    .sort_values(
        by="ai_service_count",
        ascending=False
    )
)

vendor_ai_count

  provider  ai_service_count
2      GCP                94
0      AWS                12
1    Azure                 5

In [8]:
import os

os.environ["MPLBACKEND"] = "agg"

In [9]:
import matplotlib

matplotlib.use("agg")

import matplotlib.pyplot as plt

In [11]:
import matplotlib

matplotlib.use("agg")

import matplotlib.pyplot as plt

In [13]:
import matplotlib
print(matplotlib.__file__)

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\matplotlib\__init__.py

In [14]:
pip uninstall matplotlib -y

Found existing installation: matplotlib 3.10.7
Uninstalling matplotlib-3.10.7:
  Successfully uninstalled matplotlib-3.10.7
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\~atplotlib'.
You can safely remove it manually.

In [15]:
pip install matplotlib==3.10.7

Collecting matplotlib==3.10.7
  Using cached matplotlib-3.10.7-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib==3.10.7) (1.17.0)
Using cached matplotlib-3.10.7-cp313-cp313-win_amd64.whl (8.1 MB)
Installing collected packages: matplotlib
Successfully installed matplotlib-3.10.7
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: C:\Users\user\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [17]:
pip uninstall matplotlib -y

Found existing installation: matplotlib 3.10.7
Uninstalling matplotlib-3.10.7:
  Successfully uninstalled matplotlib-3.10.7
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip install matplotlib==3.10.7

Collecting matplotlib==3.10.7
  Using cached matplotlib-3.10.7-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib==3.10.7) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib==3.10.7) (1.17.0)
Using cached matplotlib-3.10.7-cp313-cp313-win_amd64.whl (8.1 MB)
Installing collected packages: matplotlib
Successfully installed matplotlib-3.10.7
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: C:\Users\user\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [2]:
import os

if "MPLBACKEND" in os.environ:
    del os.environ["MPLBACKEND"]

In [3]:
import matplotlib

matplotlib.use("tkagg")

print(matplotlib.__version__)

3.10.7

In [8]:
import pandas as pd

In [9]:
native_service_catalog = pd.read_csv(
    "native_cloud_service_catalog.csv"
)

native_service_catalog.head()

,provider,service_code,service_name,service_title,category,source,collection_date,category_v2,category_v3
0,AWS,VMwareCloudOnAWS,VMwareCloudOnAWS,VMwareCloudOnAWS,Compute,AWS Price List Offer Index,2026-05-28,Compute,Compute
1,AWS,AWSEndUserMessaging3pFees,AWSEndUserMessaging3pFees,AWSEndUserMessaging3pFees,Messaging / Integration,AWS Price List Offer Index,2026-05-28,Other,Other
2,AWS,AWSDatabaseMigrationSvc,AWSDatabaseMigrationSvc,AWSDatabaseMigrationSvc,Database,AWS Price List Offer Index,2026-05-28,Database,Database
3,AWS,AmazonGuardDuty,AmazonGuardDuty,AmazonGuardDuty,Security,AWS Price List Offer Index,2026-05-28,Security,Other
4,AWS,AmazonApiGateway,AmazonApiGateway,AmazonApiGateway,Networking,AWS Price List Offer Index,2026-05-28,Networking,Networking

In [10]:
ai_keywords = [
    "gpu",
    "ai",
    "machine learning",
    "ml",
    "deep learning",
    "foundation model",
    "llm",
    "training",
    "inference",
    "tensor",
    "cuda",
    "neural",
    "vision",
    "nlp",
    "generative",
    "genai",
    "bedrock",
    "vertex",
    "openai",
    "hugging face"
]

In [11]:
pattern = "|".join(ai_keywords)

ai_df = native_service_catalog[
    native_service_catalog[
        "service_name"
    ]
    .str.lower()
    .str.contains(pattern, na=False)
].copy()

In [12]:
ai_df.shape

(111, 9)

In [13]:
ai_df[[
    "provider",
    "service_name",
    "category"
]].head(20)

,provider,service_name,category
7,AWS,AmazonManagedBlockchain,AI / Machine Learning
9,AWS,AmazonLookoutVision,AI / Machine Learning
10,AWS,AmazonML,AI / Machine Learning
23,AWS,AmazonBedrockService,AI / Machine Learning
25,AWS,AWSElementalMediaTailor,AI / Machine Learning
34,AWS,AmazonWorkMail,AI / Machine Learning
51,AWS,AWSCloudTrail,AI / Machine Learning
53,AWS,AmazonLightsail,AI / Machine Learning
54,AWS,AmazonBedrock,AI / Machine Learning
57,AWS,AWSSupplyChain,AI / Machine Learning
60,AWS,AmazonBedrockAgentCore,AI / Machine Learning
61,AWS,AmazonBedrockFoundationModels,AI / Machine Learning
72,Azure,Azure Container Instances,Compute
84,Azure,Azure OpenAI Service,AI / Machine Learning
85,Azure,Azure Machine Learning,AI / Machine Learning
86,Azure,Azure AI Search,AI / Machine Learning
87,Azure,Azure AI Services,AI / Machine Learning
106,GCP,Aiven for Redis,Database
111,GCP,NVIDIA GPU-Optimized VMI,Compute
117,GCP,"AI/ML development, training & inference using ...",AI / Machine Learning

In [14]:
ai_summary = (
    ai_df.groupby(
        ["provider", "category"]
    )
    .size()
    .reset_index(name="service_count")
    .sort_values(
        ["provider", "service_count"],
        ascending=[True, False]
    )
)

ai_summary

  provider               category  service_count
0      AWS  AI / Machine Learning             12
1    Azure  AI / Machine Learning              4
2    Azure                Compute              1
3      GCP  AI / Machine Learning             80
5      GCP                Compute              6
6      GCP               Database              4
4      GCP              Analytics              3
7      GCP               Security              1

In [15]:
import re
import pandas as pd

native_service_catalog = pd.read_csv("native_cloud_service_catalog.csv")

ai_patterns = [
    r"\bgpu\b",
    r"\bai\b",
    r"\bml\b",
    r"machine learning",
    r"deep learning",
    r"foundation model",
    r"\bllm\b",
    r"training",
    r"inference",
    r"tensor",
    r"cuda",
    r"neural",
    r"computer vision",
    r"\bnlp\b",
    r"generative",
    r"genai",
    r"bedrock",
    r"vertex ai",
    r"openai",
    r"sagemaker",
    r"rekognition",
    r"comprehend",
    r"lookoutvision",
    r"hugging face",
    r"tpu"
]

exclude_patterns = [
    r"blockchain",
    r"mail",
    r"trail",
    r"lightsail",
    r"supplychain",
    r"container instances",
    r"active directory",
    r"domain controller",
    r"gateway",
    r"redis",
    r"rails"
]

ai_regex = "|".join(ai_patterns)
exclude_regex = "|".join(exclude_patterns)

service_text = native_service_catalog["service_name"].str.lower()

ai_df = native_service_catalog[
    service_text.str.contains(ai_regex, regex=True, na=False) &
    ~service_text.str.contains(exclude_regex, regex=True, na=False)
].copy()

ai_df[["provider", "service_name", "category"]].head(50)

,provider,service_name,category
9,AWS,AmazonLookoutVision,AI / Machine Learning
23,AWS,AmazonBedrockService,AI / Machine Learning
31,AWS,AmazonSageMaker,AI / Machine Learning
54,AWS,AmazonBedrock,AI / Machine Learning
60,AWS,AmazonBedrockAgentCore,AI / Machine Learning
61,AWS,AmazonBedrockFoundationModels,AI / Machine Learning
84,Azure,Azure OpenAI Service,AI / Machine Learning
85,Azure,Azure Machine Learning,AI / Machine Learning
86,Azure,Azure AI Search,AI / Machine Learning
87,Azure,Azure AI Services,AI / Machine Learning
111,GCP,NVIDIA GPU-Optimized VMI,Compute
117,GCP,"AI/ML development, training & inference using ...",AI / Machine Learning
119,GCP,NVIDIA GPU-Optimized TensorFlow VMI,Compute
123,GCP,Deep Learning VM,Compute
125,GCP,Weka Machine Learning on Windows 2019,AI / Machine Learning
142,GCP,NVIDIA Image for AI using GPUs - Optimized for...,AI / Machine Learning
158,GCP,Dynamic AI Demo,AI / Machine Learning
167,GCP,LABS.AI E.D.D.I - Open Source Chatbot Platform,AI / Machine Learning
169,GCP,ThoughtSpot Search & AI-driven Analytics (BYOL),Analytics
176,GCP,H2O.ai Driverless AI (BYOL),AI / Machine Learning
184,GCP,Weka Machine Learning on Windows 2016,AI / Machine Learning
190,GCP,BizStats AI,AI / Machine Learning
197,GCP,Dace IT℠with Sense Traffic Pulse™ and Vertex AI,AI / Machine Learning
200,GCP,AISE PyTorch NVidia GPU Production,AI / Machine Learning
215,GCP,AXI AI SAP EasyConnect,AI / Machine Learning
256,GCP,Healthcare ML,AI / Machine Learning
265,GCP,Duet AI,AI / Machine Learning
268,GCP,LABS.AI E.D.D.I - Open Source Chatbot Platform,AI / Machine Learning
274,GCP,Vertex AI Search,AI / Machine Learning
276,GCP,Abzooba Inc. xpresso-ai,AI / Machine Learning
286,GCP,Cloud Contact Center AI Platform,AI / Machine Learning
304,GCP,suki-ai,AI / Machine Learning
317,GCP,Ripple Development & Training Suit,AI / Machine Learning
326,GCP,Logistic ML,AI / Machine Learning
330,GCP,NVIDIA Image for AI using GPUs - Optimized for...,AI / Machine Learning
352,GCP,Multiuser Python Jupyter notebook for AI/ML,AI / Machine Learning
355,GCP,AISE TensorFlow NVidia GPU Production,AI / Machine Learning
357,GCP,Recommendations AI,AI / Machine Learning
366,GCP,Sales ML,AI / Machine Learning
369,GCP,AXI AI Forecast ML,AI / Machine Learning
383,GCP,AXI AI SAP EasyConnect Plus,AI / Machine Learning
385,GCP,NVIDIA Image for AI using GPUs,AI / Machine Learning
387,GCP,Marketing ML,AI / Machine Learning
393,GCP,Education ML,AI / Machine Learning
397,GCP,Vertex AI,AI / Machine Learning
410,GCP,Supplier ML,AI / Machine Learning
413,GCP,Value Chain ML,AI / Machine Learning
415,GCP,Cloud Document AI API,AI / Machine Learning
422,GCP,Barracuda CloudGen Firewall (BYOL),Security
428,GCP,Cloud Machine Learning Engine,AI / Machine Learning

In [16]:
provider_ai_count = (
    ai_df.groupby("provider")
    .size()
    .reset_index(name="ai_service_count")
    .sort_values("ai_service_count", ascending=False)
)

provider_ai_count

  provider  ai_service_count
2      GCP                42
0      AWS                 6
1    Azure                 4

In [17]:
total_services = (
    native_service_catalog
    .groupby("provider")
    .size()
    .reset_index(name="total_native_services")
)

provider_ai_share = provider_ai_count.merge(
    total_services,
    on="provider"
)

provider_ai_share["ai_service_share_pct"] = (
    provider_ai_share["ai_service_count"] /
    provider_ai_share["total_native_services"] * 100
)

provider_ai_share

  provider  ai_service_count  total_native_services  ai_service_share_pct
0      GCP                42                    359             11.699164
1      AWS                 6                     69              8.695652
2    Azure                 4                     32             12.500000

In [18]:
ai_df.to_csv("ai_gpu_related_services.csv", index=False)
provider_ai_share.to_csv("provider_ai_service_share.csv", index=False)

In [19]:
def classify_service_origin(service_name):
    text = str(service_name).lower()

    native_keywords = [
        "amazon", "aws", "azure", "microsoft",
        "google", "cloud", "vertex", "gemini",
        "bedrock", "sagemaker", "openai"
    ]

    partner_keywords = [
        "byol", "bitnami", "weka", "h2o.ai",
        "thoughtspot", "labs.ai", "axi ai",
        "barracuda", "nvidia image", "jupyter",
        "pytorch", "tensorflow"
    ]

    if any(k in text for k in partner_keywords):
        return "Marketplace / Partner"
    elif any(k in text for k in native_keywords):
        return "Native Cloud Service"
    else:
        return "Unclear"

ai_df["service_origin"] = ai_df["service_name"].apply(classify_service_origin)

ai_origin_summary = (
    ai_df.groupby(["provider", "service_origin"])
    .size()
    .reset_index(name="service_count")
)

ai_origin_summary

  provider         service_origin  service_count
0      AWS   Native Cloud Service              6
1    Azure   Native Cloud Service              4
2      GCP  Marketplace / Partner             18
3      GCP   Native Cloud Service              7
4      GCP                Unclear             17

In [20]:
native_ai_df = ai_df[
    ai_df["service_origin"] == "Native Cloud Service"
].copy()

In [21]:
native_ai_count = (
    native_ai_df.groupby("provider")
    .size()
    .reset_index(name="native_ai_service_count")
)

native_ai_count

  provider  native_ai_service_count
0      AWS                        6
1    Azure                        4
2      GCP                        7

In [22]:
ai_df.to_csv("ai_gpu_related_services.csv", index=False)
provider_ai_share.to_csv("provider_ai_service_share.csv", index=False)

In [23]:
def classify_ai_type(service_name):

    text = str(service_name).lower()

    # Foundation Models
    if any(k in text for k in [
        "bedrock",
        "openai",
        "gemini",
        "llm",
        "foundation",
        "generative"
    ]):
        return "Foundation Models"

    # ML Platform
    elif any(k in text for k in [
        "sagemaker",
        "vertex ai",
        "machine learning",
        "training"
    ]):
        return "ML Platform"

    # GPU / Infrastructure
    elif any(k in text for k in [
        "gpu",
        "tpu",
        "cuda",
        "inferentia",
        "trainium"
    ]):
        return "AI Infrastructure"

    # Vision
    elif any(k in text for k in [
        "vision",
        "rekognition",
        "image"
    ]):
        return "Computer Vision"

    # NLP
    elif any(k in text for k in [
        "nlp",
        "language",
        "translate",
        "speech",
        "comprehend"
    ]):
        return "Language AI"

    else:
        return "General AI"

In [24]:
native_ai_df["ai_type"] = (
    native_ai_df["service_name"]
    .apply(classify_ai_type)
)

In [25]:
ai_type_summary = (
    native_ai_df.groupby(
        ["provider", "ai_type"]
    )
    .size()
    .reset_index(name="service_count")
)

ai_type_summary

  provider            ai_type  service_count
0      AWS    Computer Vision              1
1      AWS  Foundation Models              4
2      AWS        ML Platform              1
3    Azure  Foundation Models              1
4    Azure         General AI              2
5    Azure        ML Platform              1
6      GCP         General AI              2
7      GCP        ML Platform              5

In [26]:
native_ai_df.to_csv(
    "native_ai_services_enriched.csv",
    index=False
)

ai_type_summary.to_csv(
    "ai_type_summary.csv",
    index=False
)